export const FETCH_ALL = 'FETCH_ALL'
export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const LIKE = 'LIKE'
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'

// export const SIGNININ ='SIGNINGIN'
// export const ITEMS_LOADING = 'ITEMS_LOADING'